#!/usr/bin/env python3
"""gen_config_doc.py — generate docs/configuration.md from the plugin's own
config contract: `PgvectorMemoryProvider.get_config_schema()` (type,
default, choices, min/max, description) plus `DEFAULTS` in
`hermes_pgvector/__init__.py` (get_config_schema()'s own `default` values
are sourced from DEFAULTS, so calling it already pulls both in).

The generated table is the single source of truth for every
`plugins.pgvector.*` key; `docs/configuration.md` must never be hand-edited
around it going stale, which is why this script exists and why its
`--check` mode is wired into CI (the `versions` job).

Usage:
    python scripts/gen_config_doc.py            # (re)write docs/configuration.md
    python scripts/gen_config_doc.py --check    # exit 1 with a diff if stale, else 0

Requires the package to be importable (`pip install -e .`) — importing
`hermes_pgvector` pulls in `psycopg` and `PyYAML` at module import time via
`hermes_pgvector.store`, so this cannot run against a bare, unprepared
checkout.
"""

from __future__ import annotations

import argparse
import difflib
import sys
from pathlib import Path
from typing import Any, Dict, List

REPO_ROOT = Path(__file__).resolve().parent.parent
OUTPUT = REPO_ROOT / "docs" / "configuration.md"

# key -> the release that introduced the key's CURRENT shape/default.
# get_config_schema() deliberately carries no version field (it's a live
# contract, not a changelog) so this map is hand-maintained here; cross-check
# against CHANGELOG.md on each release that adds/changes a key. Every key
# get_config_schema() returns MUST have an entry here -- main() fails loudly
# if one is missing, rather than silently rendering "?".
SINCE_VERSION: Dict[str, str] = {
    "dsn": "0.1.0",
    "embed_url": "0.1.0",
    "embed_model": "0.1.0",
    "embed_dim": "0.5.3",
    "embed_api_key_env": "0.5.3",
    "embed_protocol": "0.5.3",
    "prefetch_limit": "0.1.0",
    "min_similarity": "0.1.0",
    "embed_on_write": "0.1.0",
    "scope_default": "0.1.0",
    "hybrid_search": "0.4.1",
    "write_queue_maxsize": "0.1.0",
    "bulk_sync_on_init": "0.1.1",
    "sync_turns": "0.2.0",
    "turn_min_chars": "0.2.0",
    "allowed_themes": "0.4.0",
    "identity_aliases": "0.4.0",
    "bench_mode": "0.4.0",
    "conversation_embed_policy": "0.4.0",
    "ttl_days": "0.4.0",
    "embed_timeout": "0.5.0",
    "embed_write_timeout": "0.5.0",
    "embed_write_retries": "0.4.0",
    "embed_write_backoff": "0.4.0",
    "write_contexts": "0.6.0",
    "shutdown_drain_timeout": "0.6.0",
    "prefetch_budget": "0.6.0",
}

HEADER = """<!-- GENERATED FILE -- DO NOT EDIT BY HAND.
     Generated by `python scripts/gen_config_doc.py` from
     `PgvectorMemoryProvider.get_config_schema()` + `DEFAULTS` in
     `hermes_pgvector/__init__.py`. Run that script (without --check) to
     regenerate after changing either one, and commit the result. CI (the
     `versions` job) runs `--check` and fails the build if this file has
     drifted. -->

# Configuration reference

Every key lives in `$HERMES_HOME/config.yaml` under `plugins.pgvector`:

```yaml
plugins:
  pgvector:
    dsn: "dbname=hermes_memory user=hermes host=/var/run/postgresql"
    embed_url: "http://localhost:11434"
    embed_model: "nomic-embed-text"
    # ... any other key below, only where the default isn't right for you
```

Every key is optional; the table shows what the plugin uses when a key is
absent. In practice almost every real deployment sets `dsn` and `embed_url`
explicitly — the rest are tuning knobs. See [README.md](../README.md) for a
worked quick-start and [scaling.md](scaling.md) for guidance on
`embed_timeout` / `prefetch_budget` / pool sizing under load.

These keys are part of the plugin's public, semver-covered contract (see
"Compatibility policy" in [README.md](../README.md)): a key is not removed,
or given an incompatible new meaning, without a major-version bump.

"""


def _default_cell(entry: Dict[str, Any]) -> str:
    default = entry.get("default")
    if default is None:
        cell = "*(none)*"
    else:
        cell = f"`{default!r}`"
    if entry.get("required"):
        cell += " — **required**"
    return cell


def _type_cell(entry: Dict[str, Any]) -> str:
    typ = entry.get("type", "text")
    bounds = ""
    lo, hi = entry.get("minimum"), entry.get("maximum")
    if lo is not None and hi is not None:
        bounds = f" ({lo}–{hi})"
    elif lo is not None:
        bounds = f" (>= {lo})"
    elif hi is not None:
        bounds = f" (<= {hi})"
    cell = f"`{typ}`{bounds}"
    choices = entry.get("choices")
    if choices:
        cell += ", one of " + ", ".join(f"`{c}`" for c in choices)
    return cell


def render(schema: List[Dict[str, Any]]) -> str:
    lines = [HEADER, "| Key | Type | Default | Since | Effect |\n",
             "|---|---|---|---|---|\n"]
    for entry in schema:
        key = entry["key"]
        since = SINCE_VERSION.get(key, "?")
        desc = entry["description"].replace("|", "\\|")
        lines.append(
            f"| `{key}` | {_type_cell(entry)} | {_default_cell(entry)} | "
            f"{since} | {desc} |\n"
        )
    lines.append("\n")
    return "".join(lines)


def load_schema() -> List[Dict[str, Any]]:
    sys.path.insert(0, str(REPO_ROOT))
    try:
        from hermes_pgvector import PgvectorMemoryProvider
    except ImportError as exc:
        print(
            f"error: could not import hermes_pgvector ({exc}). "
            "Install the package first: pip install -e .",
            file=sys.stderr,
        )
        raise SystemExit(1) from exc
    return PgvectorMemoryProvider().get_config_schema()


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check", action="store_true",
        help="exit 1 with a diff if docs/configuration.md is stale; write nothing",
    )
    args = parser.parse_args()

    schema = load_schema()
    missing = sorted(e["key"] for e in schema if e["key"] not in SINCE_VERSION)
    if missing:
        print(
            f"error: SINCE_VERSION in {Path(__file__).name} is missing an entry "
            f"for: {missing} -- add one (the release that introduced the key)",
            file=sys.stderr,
        )
        return 1

    rendered = render(schema)

    if args.check:
        if not OUTPUT.exists():
            print(
                f"MISSING: {OUTPUT} does not exist -- run "
                "`python scripts/gen_config_doc.py`",
                file=sys.stderr,
            )
            return 1
        current = OUTPUT.read_text(encoding="utf-8")
        if current != rendered:
            diff = difflib.unified_diff(
                current.splitlines(keepends=True),
                rendered.splitlines(keepends=True),
                fromfile=str(OUTPUT.relative_to(REPO_ROOT)),
                tofile="generated",
            )
            sys.stdout.writelines(diff)
            print(
                f"\nSTALE: {OUTPUT} does not match the generated output -- run "
                "`python scripts/gen_config_doc.py` and commit the result",
                file=sys.stderr,
            )
            return 1
        print(f"OK: {OUTPUT} is current")
        return 0

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(rendered, encoding="utf-8")
    print(f"wrote {OUTPUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
